/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rackserver.UI;

import rackserver.Application;
import rackserver.RunnableUtils.DigitalClock;


/**
 *
 * @author aguiz
 */
public class Overlay extends javax.swing.JFrame 
{
    private boolean overlayVisible;
    private Application context;
    public Overlay(Application context) 
    {
        this.context = context;
        initComponents();
        initFrame();
    }
    
    private void initFrame()
    {
        overlayVisible = true;
        new Thread(new DigitalClock(clockLabel)).start();
        new Thread(new TemperatureThread()).start();
        this.dispose();
        this.setUndecorated(true);
        this.setLocation(0,0);
        this.setSize(180,220);
        this.setVisible(true);
        this.pack();
        
    }
    
    private class TemperatureThread implements Runnable
    {     
        @Override
        public void run()
        {
            while(overlayVisible)
            {
                try{Thread.sleep(1000);} catch(Exception e) {};
                System.out.println("Calculating");
                tempLabel.setText(context.currentTemperature);              
            }
        }
    }
    
    public void Destroy()
    {
        overlayVisible = false;
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(180, 220));
        setResizable(false);
        setSize(new java.awt.Dimension(200, 200));

        clockLabel.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        tempLabel.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    public static javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
