/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rackserver.UI;

import java.awt.Color;
import javax.swing.JLabel;
import rackserver.RunnableUtils.DigitalClock;


/**
 *
 * @author aguiz
 */
public class Overlay extends javax.swing.JFrame 
{
    /**
     * Creates new form Background
     */
    static boolean windowCreated=false;
    
    public Overlay() 
    {
        if(!windowCreated)
        {
            initComponents();
            this.setVisible(true);
            windowCreated=true;
        }
        else
        {
            this.setVisible(true);
        }
        
        Thread clock = new Thread(new DigitalClock(clckLabel));
    }
    
    public void close()
    {
        this.setVisible(false);
        windowCreated=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clckLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(200, 300));

        clckLabel.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        tempLabel.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(clckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clckLabel;
    public static javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
